version: "3"
services:
  web:
    build: .
    container_name: web
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
  nginx:
    build: ./nginx
    ports:
      - 80:80
  pg:
    container_name: pg
    image: "postgres:alpine"
    # container_name: "next-db"
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    volumes:
      - "pg:/var/lib/postgresql/data"
    restart: "always"
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DEFAULT_WORKSPACE=/config/jdb
    volumes:
      - ./:/config/jdb
    ports:
      - 8443:8443
    restart: unless-stopped
volumes:
  pg:
