version: "3"
services:
  nextjs:
    build: ./
    # depends_on:
    #   - pg
  nginx:
    build: ./nginx
    ports:
      - 80:80
  pg:
    container_name: pg
    image: "postgres:alpine"
    # container_name: "next-db"
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    volumes:
      - "pg:/var/lib/postgresql/data"
    restart: "always"
volumes:
  pg:
