version: "3"
services:
  web:
    build: .
    container_name: web
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
  nginx:
    build: ./nginx
    ports:
      - 80:80
  pg:
    container_name: pg
    image: "postgres:alpine"
    # container_name: "next-db"
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    volumes:
      - "pg:/var/lib/postgresql/data"
    restart: "always"
volumes:
  pg:
